// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace APIJessicaOliveira2.Models;

public partial class Aluno
{
    public string Cpf { get; set; }

    public string Nome { get; set; }

    public DateOnly DataDeNascimento { get; set; }

    public string Nota { get; set; }

    public string Disciplina { get; set; }

    public string Faltas { get; set; }

    public int Id { get; set; }

    public string Email { get; set; }

    public string Senha { get; set; }

    [JsonIgnore]
    public virtual ICollection<Horario> Horarios { get; set; } = new List<Horario>();
    [JsonIgnore]
    public virtual ICollection<Notas> Notas { get; set; } = new List<Notas>();
}