// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIJessicaOliveira2.Models;

public partial class Disciplina
{
    public Disciplina()
    {
        Horarios = new HashSet<Horario>();
    }

    public int Codigo { get; set; }

    public string Nome { get; set; }

    public virtual ICollection<Horario> Horarios { get; set; }
}