// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIJessicaOliveira2.Models;

public partial class EndereçoAluno
{
    public int Id;
    public string Logradouro { get; set; }

    public string Cidade { get; set; }

    public string Estado { get; set; }

    public string Cpf { get; set; }

    public virtual Aluno Cpfs { get; set; }
}