// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace APIJessicaOliveira2.Models;

public partial class EndereçoProfessor
{
    public int Id { get; set; }
    public string Logradouro { get; set; }

    public string Cpf { get; set; }

    public string Cidade { get; set; }

    public string Estado { get; set; }
    [JsonIgnore]
    public virtual Professor Cpfs { get; set; }
}