// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIJessicaOliveira2.Models;

public partial class EndereçoProfessor
{
    public string Logradouro { get; set; }

    public string Cpf { get; set; }

    public string Cidade { get; set; }

    public string Estado { get; set; }

    public virtual Professor Cpfs { get; set; }
}