// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIJessicaOliveira2.Models;

public partial class Escola
{
    public string Cpnj { get; set; }

    public string Nome { get; set; }

    public string Endereço { get; set; }

    public string Telefone { get; set; }
}