// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIJessicaOliveira2.Models;

public partial class Financeiro
{
    public decimal ValorBoleto { get; set; }

    public DateTime DataBoleto { get; set; }

    public string Cpf { get; set; }

    public string SituacaoPagamento { get; set; }

    public virtual Aluno Cpfs { get; set; }
}