// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIJessicaOliveira2.Models;

public partial class Horario
{
    public int Codigo { get; set; }

    public int CodigoDisciplina { get; set; }

    public int NumeroSala { get; set; }

    public string Cpfaluno { get; set; }

    public string Cpfprofessor { get; set; }

    public virtual Disciplina Disciplina { get; set; }

    public virtual Aluno CpfsAlunos { get; set; }

    public virtual Professor Cpfsprofessor { get; set; }

    public virtual SalaDeAula NumeroSalas { get; set; }
}