// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIJessicaOliveira2.Models;

public partial class Notas
{
    public int Codigo { get; set; }

    public string Nota { get; set; }

    public string Cpf { get; set; }

    public virtual Aluno CpfsAlunos { get; set; }
}