// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace APIJessicaOliveira2.Models;

public partial class PlanoDeAula
{
    public int Id { get; set; }
    public string Codigo { get; set; }

    public string Cpfprofessor { get; set; }

    public int NumeroSala { get; set; }

    public string Musica { get; set; }
    [JsonIgnore]
    public virtual Professor Cpfsprofessor { get; set; }
    [JsonIgnore]
    public virtual SalaDeAula NumeroSalas { get; set; }
}